<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SH852" ignored="0" name="Default test" tests="2" failures="2" timestamp="19 六月 2017 11:42:54 GMT" time="32.056" errors="0">
  <testcase name="loginTest01" time="14.453" classname="com.xiaoyun.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:56)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:70)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:68)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:89)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest01(LoginTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loginTest01 -->
  <testcase name="loginTest02" time="10.799" classname="com.xiaoyun.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:56)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:70)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:68)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:89)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest02(LoginTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loginTest02 -->
</testsuite> <!-- Default test -->
