<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="2" ignored="0" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite1" duration-ms="135106" started-at="2017-06-19T11:53:53Z" finished-at="2017-06-19T11:56:08Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="135106" started-at="2017-06-19T11:53:53Z" finished-at="2017-06-19T11:56:08Z">
      <class name="com.xiaoyun.testcases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="setUp" is-config="true" duration-ms="12748" started-at="2017-06-19T19:53:53Z" finished-at="2017-06-19T19:54:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="loginTest01()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest01" duration-ms="46453" started-at="2017-06-19T19:54:06Z" finished-at="2017-06-19T19:54:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest01(LoginTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest01 -->
        <test-method status="SKIP" signature="loginTest01()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest01" duration-ms="28786" started-at="2017-06-19T19:54:53Z" finished-at="2017-06-19T19:55:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest01(LoginTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest01 -->
        <test-method status="FAIL" signature="loginTest01()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest01" duration-ms="11089" started-at="2017-06-19T19:55:21Z" finished-at="2017-06-19T19:55:32Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest01(LoginTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest01 -->
        <test-method status="SKIP" signature="loginTest02()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest02" duration-ms="11031" started-at="2017-06-19T19:55:32Z" finished-at="2017-06-19T19:55:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest02(LoginTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest02 -->
        <test-method status="SKIP" signature="loginTest02()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest02" duration-ms="10778" started-at="2017-06-19T19:55:43Z" finished-at="2017-06-19T19:55:54Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest02(LoginTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest02 -->
        <test-method status="FAIL" signature="loginTest02()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="loginTest02" duration-ms="10728" started-at="2017-06-19T19:55:54Z" finished-at="2017-06-19T19:56:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:43)
	at com.xiaoyun.utils.ScreenShot.takeScreenShot(ScreenShot.java:38)
	at com.xiaoyun.uiframework.webElementUtil.getElement(webElementUtil.java:57)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:71)
	at com.xiaoyun.uiframework.webElementUtil$1.apply(webElementUtil.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.xiaoyun.uiframework.webElementUtil.findElement(webElementUtil.java:69)
	at com.xiaoyun.uiframework.webElementUtil.click(webElementUtil.java:90)
	at com.xiaoyun.pages.LoginPage.Login(LoginPage.java:86)
	at com.xiaoyun.actions.LoginOperate.LoginSuess(LoginOperate.java:30)
	at com.xiaoyun.actions.LoginOperate.getLoginName(LoginOperate.java:42)
	at com.xiaoyun.testcases.LoginTest.loginTest02(LoginTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.xiaoyun.testcases.LoginTest@663c9e7a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2017-06-19T19:56:05Z" finished-at="2017-06-19T19:56:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.xiaoyun.testcases.LoginTest -->
    </test> <!-- test1 -->
  </suite> <!-- suite1 -->
</testng-results>
